name: Infracost Scan

on:
  push:
    branches:
      - project/cloudtasks
      - project/cloudtasks-staging
      - project/cloudtasks-prod
    paths:
      - "cloudtasks/terraform/**"
      - "cloudtasks/infracost.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  infracost-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Infracost Scan
        uses: infracost/actions/scan@v4
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          path: cloudtasks