name: Infracost Diff

on:
  pull_request:
    branches:
      - project/cloudtasks
      - project/cloudtasks-staging
      - project/cloudtasks-prod
    paths:
      - "cloudtasks/terraform/**"
      - "cloudtasks/infracost.yml"
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head branch
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          path: head

      - name: Checkout base branch
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base

      - name: Run Infracost Diff
        if: github.event.action != 'closed'
        uses: infracost/actions/diff@v4
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          base-path: base
          head-path: head

      - name: Update pull request status
        if: github.event.action == 'closed'
        uses: infracost/actions/diff@v4
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          pr-status: ${{ github.event.pull_request.merged && 'MERGED' || 'CLOSED' }}